export const allregex: {
  [key: string]: {
    findmode: string;
    type?: string;
    nm?: string;
    param?: string;
    caption: string;
    ex: string;
    rgx: string[];
  };
} = {
  lambda: {
    findmode: "ast",
    type: "node",
    nm: "Lambda",
    param: "",
    caption: "lambda",
    ex: "",
    rgx: [""],
  },
  fline: {
    findmode: "ast",
    type: "node",
    nm: "JoinedStr",
    param: "",
    caption: "f-строки",
    ex: "Пример: f'Привет, {a}",
    rgx: ["f[\\\"']{1,3}"],
  },
  continue: {
    findmode: "ast",
    type: "node",
    nm: "Continue",
    param: "",
    caption: "continue",
    ex: "",
    rgx: [""],
  },
  break: {
    findmode: "ast",
    type: "node",
    nm: "Break",
    param: "",
    caption: "break",
    ex: "",
    rgx: [""],
  },
  for: {
    findmode: "ast",
    type: "node",
    nm: "For",
    param: "",
    caption: "цикл for",
    ex: "Нет примера",
    rgx: ["\\bfor\\b"],
  },
  while: {
    findmode: "ast",
    type: "node",
    nm: "While",
    param: "",
    caption: "цикл while",
    ex: "Нет примера",
    rgx: ["\\bfor\\b"],
  },
  condition: {
    findmode: "ast",
    type: "node",
    nm: "If",
    param: "",
    caption: "условие",
    ex: "Нет примера",
    rgx: ["\\bif\\b"],
  },
  listcomp: {
    findmode: "ast",
    type: "node",
    nm: "ListComp",
    param: "",
    caption: "списковые включения",
    ex: "Пример: [i for i in range(a)]",
    rgx: ["[\\[\\(].*?\\bfor\\b\\s+.*?\\bin\\b.*?[\\]\\)]"],
  },
  GeneratorExp: {
    findmode: "ast",
    type: "node",
    nm: "GeneratorExp",
    param: "",
    caption: "генераторы",
    ex: "Пример: (i for i in range(a))",
    rgx: ["[\\[\\(].*?\\bfor\\b\\s+.*?\\bin\\b.*?[\\]\\)]"],
  },
  slices: {
    findmode: "ast",
    type: "node",
    nm: "Slice",
    param: "",
    caption: "срезы",
    ex: "Пример: a=b[1:5:-1]",
    rgx: ["\\[[^\\]\\[]*:[^\\]\\[]*\\]"],
  },
  ternary: {
    findmode: "ast",
    type: "node",
    nm: "IfExp",
    param: "",
    caption: "тернарный оператор",
    ex: "Пример: a if a>b else b",
    rgx: ["if[^:]*else"],
  },
  def: {
    findmode: "ast",
    type: "node",
    nm: "FunctionDef",
    param: "",
    caption: "Библиотеки python",
    ex: "",
    rgx: ["\\bimport\\b"],
  },
  tuple: {
    findmode: "ast",
    type: "node",
    nm: "Tuple",
    param: "",
    caption: "Кортежи",
    ex: "",
    rgx: [""],
  },
  list: {
    findmode: "ast",
    type: "node",
    nm: "List",
    param: "",
    caption: "Списки",
    ex: "",
    rgx: [""],
  },
  try: {
    findmode: "ast",
    type: "node",
    nm: "Try",
    param: "",
    caption: "try except",
    ex: "",
    rgx: [""],
  },
  dict: {
    findmode: "ast",
    type: "dict",
    nm: "Dict",
    param: "",
    caption: "словарь",
    ex: "Нет примера",
    rgx: [""],
  },
  namedargs: {
    findmode: "ast",
    type: "namedargs",
    nm: "",
    param: "",
    caption: "именованные аргументы",
    ex: "Нет примера",
    rgx: [""],
  },
  recursion: {
    findmode: "ast",
    type: "recursion",
    nm: "",
    param: "",
    caption: "рекурсия",
    ex: "Пример: пока нет",
    rgx: [""],
  },
  forelse: {
    findmode: "ast",
    type: "forelse",
    nm: "",
    param: "",
    caption: "for ... else",
    ex: "Пример: пока нет",
    rgx: [""],
  },
  setfunc: {
    findmode: "ast",
    type: "function",
    nm: "set",
    param: "",
    caption: "функция set",
    ex: "Пример: пока нет",
    rgx: [""],
  },
  forin: {
    findmode: "ast",
    type: "find_for_in_not_range",
    nm: "",
    param: "",
    caption: "for in",
    ex: "Нет примера",
    rgx: ["\\bfor\\b\\s+.+\\bin\\b\\s+(?!range\\b)"],
  },
  starincall: {
    findmode: "ast",
    type: "starincall",
    nm: "",
    param: "",
    caption: "распаковка звездочкой",
    ex: "нет",
    rgx: [""],
  },
  index: {
    findmode: "ast",
    type: "index",
    nm: "",
    param: "",
    caption: "индексы",
    ex: "Пример: a=b[2]",
    rgx: ["\\[.*?\\]"],
  },
  unpackass: {
    findmode: "ast",
    type: "unpackass",
    nm: "",
    param: "",
    caption: "параллельное присваивание",
    ex: "нет",
    rgx: [""],
  },
  ifin: {
    findmode: "ast",
    type: "ifin",
    nm: "",
    param: "",
    caption: "логический оператор in в условии",
    ex: "Пример: if a in b: print(a)",
    rgx: ["if.*?\\bin\\b.*:"],
  },
  name1: {
    findmode: "ast",
    type: "variable",
    nm: "name1",
    param: "",
    caption: "переменная name1",
    ex: "Примера нет",
    rgx: [""],
  },
  name2: {
    findmode: "ast",
    type: "variable",
    nm: "name2",
    param: "",
    caption: "переменная name2",
    ex: "Примера нет",
    rgx: [""],
  },
  name: {
    findmode: "ast",
    type: "variable",
    nm: "name",
    param: "",
    caption: "переменная name",
    ex: "Примера нет",
    rgx: [""],
  },
  cache: {
    findmode: "ast",
    type: "decorator",
    nm: "cache",
    param: "",
    caption: "cache",
    ex: "",
    rgx: [""],
  },
  import: {
    findmode: "ast",
    type: "import",
    nm: "",
    param: "",
    caption: "Библиотеки python",
    ex: "",
    rgx: ["\\bimport\\b"],
  },
  collections: {
    findmode: "ast",
    type: "importmodule",
    nm: "collections",
    param: "",
    caption: "Библиотека collections",
    ex: "",
    rgx: [""],
  },
  itertools: {
    findmode: "ast",
    type: "importmodule",
    nm: "itertools",
    param: "",
    caption: "Библиотека itertools",
    ex: "",
    rgx: [""],
  },
  punctuation: {
    findmode: "ast",
    type: "importspec",
    nm: "string",
    param: "punctuation",
    caption: "punctuation",
    ex: "Нет примера",
    rgx: [""],
  },
  digits: {
    findmode: "ast",
    type: "importspec",
    nm: "string",
    param: "digits",
    caption: "digits",
    ex: "Нет примера",
    rgx: [""],
  },
  ascii_uppercase: {
    findmode: "ast",
    type: "importspec",
    nm: "string",
    param: "ascii_uppercase",
    caption: "ascii_uppercase",
    ex: "Нет примера",
    rgx: [""],
  },
  ascii_lowercase: {
    findmode: "ast",
    type: "importspec",
    nm: "string",
    param: "ascii_lowercase",
    caption: "ascii_lowercase",
    ex: "Нет примера",
    rgx: [""],
  },
  ascii_letters: {
    findmode: "ast",
    type: "importspec",
    nm: "string",
    param: "ascii_letters",
    caption: "ascii_letters",
    ex: "Нет примера",
    rgx: [""],
  },
  capwords: {
    findmode: "ast",
    type: "importspec",
    nm: "string",
    param: "capwords",
    caption: "capwords",
    ex: "Нет примера",
    rgx: [""],
  },
  append: {
    findmode: "ast",
    type: "method",
    nm: "append",
    param: "",
    caption: "списки",
    ex: "Пример, a.append(b), print(a[i])",
    rgx: ["\\.\\s*\\bappend\\b\\s*\\(.*?\\)"],
  },
  join: {
    findmode: "ast",
    type: "method",
    nm: "join",
    param: "",
    caption: "join",
    ex: "Пример: a=''.join(b)",
    rgx: ["join\\s*\\(.*?\\)"],
  },
  split: {
    findmode: "ast",
    type: "method",
    nm: "split",
    param: "",
    caption: "split",
    ex: "Пример: a=b.split()",
    rgx: ["\\bsplit\\b\\s*\\(.*?\\)|\\bsplit\\b"],
  },
  find: {
    findmode: "ast",
    type: "method",
    nm: "find",
    param: "",
    caption: "find",
    ex: "Пример: a=b.find('A')",
    rgx: ["\\bfind\\b\\s*\\(.*?\\)|\\bfind\\b"],
  },
  rfind: {
    findmode: "ast",
    type: "method",
    nm: "rfind",
    param: "",
    caption: "rfind",
    ex: "Пример: a=b.rfind('A')",
    rgx: ["\\brfind\\b\\s*\\(.*?\\)|\\brfind\\b"],
  },
  strip: {
    findmode: "ast",
    type: "method",
    nm: "strip",
    param: "",
    caption: "strip",
    ex: "Нет примера",
    rgx: ["\\bstrip\\b\\s*\\(.*?\\)|\\bstrip\\b"],
  },
  startswith: {
    findmode: "ast",
    type: "method",
    nm: "startswith",
    param: "",
    caption: "startswith",
    ex: "Нет примера",
    rgx: [""],
  },
  endswith: {
    findmode: "ast",
    type: "method",
    nm: "endswith",
    param: "",
    caption: "endswith",
    ex: "Нет примера",
    rgx: [""],
  },
  replace: {
    findmode: "ast",
    type: "method",
    nm: "replace",
    param: "",
    caption: "replace",
    ex: "Пример: a=a.replace('A','B')",
    rgx: ["\\breplace\\b\\s*\\(.*?\\)|\\breplace\\b"],
  },
  count: {
    findmode: "ast",
    type: "method",
    nm: "count",
    param: "",
    caption: "count",
    ex: "Пример: a.count('A')",
    rgx: ["\\bcount\\b\\s*\\(.*?\\)|\\bcount\\b"],
  },
  ceil: {
    findmode: "ast",
    type: "method",
    nm: "ceil",
    param: "",
    caption: "ceil",
    ex: "Нет примера",
    rgx: [""],
  },
  floor: {
    findmode: "ast",
    type: "method",
    nm: "ceil",
    param: "",
    caption: "floor",
    ex: "Нет примера",
    rgx: [""],
  },
  isnumeric: {
    findmode: "ast",
    type: "method",
    nm: "isnumeric",
    param: "",
    caption: "isnumeric",
    ex: "Нет примера",
    rgx: [""],
  },
  upper: {
    findmode: "ast",
    type: "method",
    nm: "upper",
    param: "",
    caption: "upper",
    ex: "Нет примера",
    rgx: [""],
  },
  lower: {
    findmode: "ast",
    type: "method",
    nm: "lower",
    param: "",
    caption: "lower",
    ex: "Нет примера",
    rgx: [""],
  },
  islower: {
    findmode: "ast",
    type: "method",
    nm: "islower",
    param: "",
    caption: "islower",
    ex: "Нет примера",
    rgx: [""],
  },
  isupper: {
    findmode: "ast",
    type: "method",
    nm: "isupper",
    param: "",
    caption: "isupper",
    ex: "Нет примера",
    rgx: [""],
  },
  capitalize: {
    findmode: "ast",
    type: "method",
    nm: "capitalize",
    param: "",
    caption: "capitalize",
    ex: "Нет примера",
    rgx: [""],
  },
  casefold: {
    findmode: "ast",
    type: "method",
    nm: "casefold",
    param: "",
    caption: "casefold",
    ex: "Нет примера",
    rgx: [""],
  },
  lstrip: {
    findmode: "ast",
    type: "method",
    nm: "lstrip",
    param: "",
    caption: "lstrip",
    ex: "Нет примера",
    rgx: [""],
  },
  rstrip: {
    findmode: "ast",
    type: "method",
    nm: "rstrip",
    param: "",
    caption: "rstrip",
    ex: "Нет примера",
    rgx: [""],
  },
  ljust: {
    findmode: "ast",
    type: "method",
    nm: "ljust",
    param: "",
    caption: "ljust",
    ex: "Нет примера",
    rgx: [""],
  },
  rjust: {
    findmode: "ast",
    type: "method",
    nm: "rjust",
    param: "",
    caption: "rjust",
    ex: "Нет примера",
    rgx: [""],
  },
  zfill: {
    findmode: "ast",
    type: "method",
    nm: "zfill",
    param: "",
    caption: "zfill",
    ex: "Нет примера",
    rgx: [""],
  },
  fnmatch: {
    findmode: "ast",
    type: "method",
    nm: "fnmatch",
    param: "",
    caption: "fnmatch",
    ex: "Нет примера",
    rgx: [""],
  },
  items: {
    findmode: "ast",
    type: "method",
    nm: "items",
    param: "",
    caption: "items",
    ex: "Нет примера",
    rgx: [""],
  },
  Counter: {
    findmode: "ast",
    type: "method",
    nm: "Counter",
    param: "",
    caption: "Counter",
    ex: "Нет примера",
    rgx: [""],
  },
  most_common: {
    findmode: "ast",
    type: "method",
    nm: "most_common",
    param: "",
    caption: "most_common",
    ex: "Нет примера",
    rgx: [""],
  },
  permutations: {
    findmode: "ast",
    type: "method",
    nm: "permutations",
    param: "",
    caption: "permutations",
    ex: "Нет примера",
    rgx: [""],
  },
  product: {
    findmode: "ast",
    type: "method",
    nm: "product",
    param: "",
    caption: "product",
    ex: "Нет примера",
    rgx: [""],
  },
  combinations: {
    findmode: "ast",
    type: "method",
    nm: "combinations",
    param: "",
    caption: "combinations",
    ex: "Нет примера",
    rgx: [""],
  },
  combinations_with_replacement: {
    findmode: "ast",
    type: "method",
    nm: "combinations_with_replacement",
    param: "",
    caption: "combinations_with_replacement",
    ex: "Нет примера",
    rgx: [""],
  },
  keys: {
    findmode: "ast",
    type: "method",
    nm: "keys",
    param: "",
    caption: "keys",
    ex: "Нет примера",
    rgx: [""],
  },
  values: {
    findmode: "ast",
    type: "method",
    nm: "values",
    param: "",
    caption: "values",
    ex: "Нет примера",
    rgx: [""],
  },
  NotEq: {
    findmode: "ast",
    type: "compare",
    nm: "NotEq",
    param: "",
    caption: "neq",
    ex: "Нет примера",
    rgx: ["!="],
  },
  add: {
    findmode: "ast",
    type: "operation",
    nm: "add",
    param: "",
    caption: "плюс",
    ex: "Нет примера",
    rgx: ["\\+"],
  },
  sub: {
    findmode: "ast",
    type: "operation",
    nm: "sub",
    param: "",
    caption: "минус",
    ex: "Нет примера",
    rgx: ["-"],
  },
  floorDiv: {
    findmode: "ast",
    type: "operation",
    nm: "floorDiv",
    param: "",
    caption: "деление нацело",
    ex: "Нет примера",
    rgx: ["\\/\\/"],
  },
  div: {
    findmode: "ast",
    type: "operation",
    nm: "div",
    param: "",
    caption: "деление",
    ex: "Нет примера",
    rgx: ["\\/\\/"],
  },
  pow: {
    findmode: "ast",
    type: "operation",
    nm: "pow",
    param: "",
    caption: "степень",
    ex: "Нет примера",
    rgx: ["\\*\\*"],
  },
  mult: {
    findmode: "ast",
    type: "operation",
    nm: "mult",
    param: "",
    caption: "умножение",
    ex: "Нет примера",
    rgx: ["\\*"],
  },
  mod: {
    findmode: "ast",
    type: "operation",
    nm: "mod",
    param: "",
    caption: "остаток",
    ex: "Нет примера",
    rgx: ["%"],
  },
  or: {
    findmode: "ast",
    type: "operation",
    nm: "or",
    param: "",
    caption: "or",
    ex: "Нет примера",
    rgx: ["\\bor\\b"],
  },
  and: {
    findmode: "ast",
    type: "operation",
    nm: "and",
    param: "",
    caption: "and",
    ex: "Нет примера",
    rgx: ["\\band\\b"],
  },
  not: {
    findmode: "ast",
    type: "operation",
    nm: "not",
    param: "",
    caption: "not",
    ex: "Нет примера",
    rgx: ["\\bnot\\b"],
  },
  end: {
    findmode: "ast",
    type: "function",
    nm: "print",
    param: "end",
    caption: "end",
    ex: "Нет примера",
    rgx: ["print\\s*\\(.*?end\\s*=\\s*[\\\"'].*?[\\\"'].*?\\)"],
  },
  sep: {
    findmode: "ast",
    type: "function",
    nm: "print",
    param: "sep",
    caption: "sep",
    ex: "Нет примера",
    rgx: ["print\\s*\\(.*?sep\\s*=\\s*[\\\"'].*?[\\\"'].*?\\)"],
  },
  keymax: {
    findmode: "ast",
    type: "function",
    nm: "max",
    param: "key",
    caption: "ключ в max",
    ex: "Нет примера",
    rgx: [""],
  },
  keymin: {
    findmode: "ast",
    type: "function",
    nm: "min",
    param: "key",
    caption: "ключ в min",
    ex: "Нет примера",
    rgx: [""],
  },
  keysorted: {
    findmode: "ast",
    type: "function",
    nm: "sorted",
    param: "key",
    caption: "ключ в sorted",
    ex: "Нет примера",
    rgx: [""],
  },
  map: {
    findmode: "ast",
    type: "function",
    nm: "map",
    param: "",
    caption: "map",
    ex: "Пример: map(int, a)",
    rgx: ["\\bmap\\b\\s*\\(.*?\\)|\\bmap\\b"],
  },
  all: {
    findmode: "ast",
    type: "function",
    nm: "all",
    param: "",
    caption: "all",
    ex: "",
    rgx: [""],
  },
  any: {
    findmode: "ast",
    type: "function",
    nm: "any",
    param: "",
    caption: "any",
    ex: "",
    rgx: [""],
  },
  sum: {
    findmode: "ast",
    type: "function",
    nm: "sum",
    param: "",
    caption: "sum",
    ex: "Пример: sum([1,2,3])",
    rgx: ["\\bsum\\b\\s*\\(.*?\\)|\\bsum\\b"],
  },
  max: {
    findmode: "ast",
    type: "function",
    nm: "max",
    param: "",
    caption: "max",
    ex: "Пример: max([1,2,3])",
    rgx: ["\\bmax\\b\\s*\\(.*?\\)|\\bmax\\b"],
  },
  min: {
    findmode: "ast",
    type: "function",
    nm: "min",
    param: "",
    caption: "min",
    ex: "Пример: min([1,2,3]",
    rgx: ["\\bmin\\b\\s*\\(.*?\\)|\\bmin\\b"],
  },
  len: {
    findmode: "ast",
    type: "function",
    nm: "len",
    param: "",
    caption: "len",
    ex: "Пример: len([1,2,3]),len('ABC')",
    rgx: ["\\blen\\b\\s*\\(.*?\\)|\\blen\\b"],
  },
  listfunc: {
    findmode: "ast",
    type: "function",
    nm: "list",
    param: "",
    caption: "list",
    ex: "Пример: list('ABC')",
    rgx: ["\\blist\\b\\s*\\(.*?\\)|\\blist\\b"],
  },
  sorted: {
    findmode: "ast",
    type: "function",
    nm: "sorted",
    param: "",
    caption: "sorted",
    ex: "Нет примера",
    rgx: ["\\bsorted\\b\\s*\\(.*?\\)|\\bsorted\\b"],
  },
  int: {
    findmode: "ast",
    type: "function",
    nm: "int",
    param: "",
    caption: "int",
    ex: "Нет примера",
    rgx: ["\\bint\\b\\s*\\(.*?\\)|\\bint\\b"],
  },
  str: {
    findmode: "ast",
    type: "function",
    nm: "str",
    param: "",
    caption: "str",
    ex: "Нет примера",
    rgx: ["\\bstr\\b\\s*\\(.*?\\)|\\bstr\\b"],
  },
  set: {
    findmode: "ast",
    type: "function",
    nm: "set",
    param: "",
    caption: "set",
    ex: "Нет примера",
    rgx: [""],
  },
  ord: {
    findmode: "ast",
    type: "function",
    nm: "ord",
    param: "",
    caption: "ord",
    ex: "Нет примера",
    rgx: [""],
  },
  chr: {
    findmode: "ast",
    type: "function",
    nm: "chr",
    param: "",
    caption: "chr",
    ex: "Нет примера",
    rgx: [""],
  },
  zip: {
    findmode: "ast",
    type: "function",
    nm: "zip",
    param: "",
    caption: "zip",
    ex: "Нет примера",
    rgx: [""],
  },
  eval: {
    findmode: "ast",
    type: "function",
    nm: "eval",
    param: "",
    caption: "eval",
    ex: "Нет примера",
    rgx: [""],
  },
  abs: {
    findmode: "ast",
    type: "function",
    nm: "abs",
    param: "",
    caption: "eval",
    ex: "Нет примера",
    rgx: [""],
  },
};
