export const CODERUN_PNL_HT = 50;
export const CODERUN_IN_OUT_HT = 175;
export const CODERUN_IN_OUT_TOTAL_HT_ISMOBILE =
  CODERUN_IN_OUT_HT * 2 + CODERUN_PNL_HT;
export const CODERUN_IN_OUT_TOTAL_HT = CODERUN_IN_OUT_HT + CODERUN_PNL_HT;
export const TOP_PANEL_HEIGHT = 80;
