export const EditorOptions = {
  automaticLayout: true,
  contextmenu: false,
  dragAndDrop: false,
  dropIntoEditor: {
    enabled: false,
  },
  detectIndentation: false,
  fixedOverflowWidgets: false,
  fontFamily: "Monaco",
  fontSize: 16,
  formatOnPaste: true,
  formatOnType: true,
  lineHeight: 1.5,
  renderLineHighlight: "none",
  renderIndentGuides: false,
  overviewRulerLanes: 0,
  minimap: {
    enabled: false,
  },
  padding: {
    top: 8,
    button: 8,
  },
  scrollbar: {
    verticalScrollbarSize: 9,
    horizontalScrollbarSize: 9,
    alwaysConsumeMouseWheel: false,
  },
  scrollBeyondLastLine: false,
  smoothScrolling: true,
  tabSize: 4,
  quickSuggestions: true,
  wordBasedSuggestions: true,
};
