const rows2 = [
  { id: 1, name: "Тест 1", pts: 0, change: 0 },
  { id: 2, name: "Тест 2", pts: 0, change: 0 },
  { id: 3, name: "Тест 3", pts: 0, change: 0 },
  { id: 4, name: "Тест 4", pts: 20, change: 0 },
  { id: 5, name: "Тест 5", pts: 21, change: 0 },
  { id: 6, name: "Тест 6", pts: 0, change: 0 },
  { id: 7, name: "Тест 7", pts: 10, change: 0 },
  { id: 8, name: "Тест 8", pts: 0, change: 0 },
  { id: 9, name: "Тест 9", pts: 0, change: 0 },
  { id: 10, name: "Тестsdfa faf 1", pts: 12, change: 0 },
  { id: 11, name: "Тест adfasdfa  1", pts: 0, change: 0 },
  { id: 12, name: "Тестsdf 1", pts: 0, change: 0 },
  { id: 13, name: "Тестsdf 1", pts: 0, change: 0 },
  { id: 14, name: "Тестs 1", pts: 0, change: 0 },
  { id: 15, name: "Тест 1sdf", pts: 0, change: 0 },
  { id: 16, name: "Тест 1sdf", pts: 0, change: 0 },
];
